#!/usr/bin/env php
<?php
assert_options(ASSERT_ACTIVE, 1);
assert_options(ASSERT_WARNING, 0);

$file = file('README.md');
$assertions = array();
$assertions[] = assert("'{$file[0]}' == 'Ana Hevesi\n'");
$assertions[] = assert("'{$file[1]}' == '==========\n'");
$assertions[] = assert("'{$file[2]}' == '\n'");
$assertions[] = assert("'{$file[3]}' == 'Hi, my name is Ana Hevesi!\n'");

foreach ($assertions as $assertion=>$result) {
    $result = booleanString($result);
    echo "Asserttion {$assertion} = {$result}\n";
}

function booleanString($bool)
{
    switch ($bool) {
        case true:
            return "passed";
            break;
        default:
            return "failed";
            break;
    }
}
